apiVersion: v1
kind: Service
metadata:
  namespace: kube-system
  name: sonar-postgresql-service
  labels:
    run: sonar-postgresql
spec:
  #type: NodePort
  ports: 
  - port: 5432
    #nodePort: 30306
    #protocol: TCP
  selector:
    run: sonar-postgresql
