apiVersion: v1
kind: Service
metadata:
  namespace: kube-system
  name: sonar-service
  labels:
    run: sonar
spec:
  type: NodePort
  ports: 
  - port: 9000
    nodePort: 30096
    protocol: TCP
  selector:
    run: sonar
